version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.56
    ports:
      - "16686:16686"   # Jaeger UI
      - "6831:6831/udp" # UDP 端口（接收 Jaeger 协议数据）
      - "6832:6832/udp"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
